# Super Linter configuration file

# Disable PowerShell script validation
DISABLE_POWERSHELL: true

# Disable Python Black linter
DISABLE_PYTHON_BLACK: true

# Disable Flake8 (Python linting)
DISABLE_PYTHON_FLAKE8: true

# (Optional) If you want to disable ALL Python linting:
# DISABLE_PYTHON: true
