name: Super-Linter

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Run Super-Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Super-Linter
        uses: github/super-linter@v5
        env:
          DISABLE_POWERSHELL: true  # Disable PowerShell script validation
          DISABLE_PYTHON_BLACK: true  # Disables Black linter for Python
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
