name: Super-Linter

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Run Super-Linter
    runs-on: ubuntu-latest
    env:
      DISABLE_POWERSHELL: true  # Disable PowerShell script validation
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Super-Linter
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
