name: Test Run API

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-run:
    name: Run FastAPI in Container
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build -t evalcompanyapi:latest .

      - name: Run Docker Container
        run: |
          docker run -d -p 8000:8000 --name evalapi evalcompanyapi:latest
          sleep 5  # Give FastAPI some time to start

      - name: Test API Endpoint
        run: |
          curl --fail http://127.0.0.1:8000/docs

      - name: Stop and Remove Container
        if: always()
        run: |
          docker stop evalapi
          docker rm evalapi
